swagger: "2.0"

info:
  title: Swagger Webhook PoC
  version: "1.0.0"
  description: "<img src='SEU_WEBHOOK' />"

paths:
  /ping:
    get:
      summary: Webhook test endpoint
      responses:
        "200":
          description: OK
